export const events = [
  {
    slug: "lagos-tech-fest-2026",
    image: "/images/event1.png",
    title: "Lagos Tech Fest 2026",
    location: "Lagos, Nigeria",
    date: "May 10, 2026",
    time: "9:00 AM - 5:00 PM",
  },
  {
    slug: "react-lagos-meetup",
    image: "/images/event2.png",
    title: "React Lagos Meetup",
    location: "Yaba, Lagos",
    date: "April 20, 2026",
    time: "4:00 PM - 7:00 PM",
  },
  {
    slug: "abuja-dev-summit",
    image: "/images/event3.png",
    title: "Abuja Developers Summit",
    location: "Abuja, Nigeria",
    date: "June 5, 2026",
    time: "10:00 AM - 6:00 PM",
  },
  {
    slug: "naija-ai-hackathon",
    image: "/images/event4.png",
    title: "Naija AI Hackathon",
    location: "Lagos, Nigeria",
    date: "July 12-14, 2026",
    time: "48 Hours",
  },
  {
    slug: "web3-lagos-conference",
    image: "/images/event5.png",
    title: "Web3 Lagos Conference",
    location: "Victoria Island, Lagos",
    date: "August 3, 2026",
    time: "9:00 AM - 5:00 PM",
  },
  {
    slug: "fullstack-africa",
    image: "/images/event6.png",
    title: "Fullstack Africa Conference",
    location: "Lagos, Nigeria",
    date: "September 18, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "devops-africa",
    image: "/images/event1.png",
    title: "DevOps Africa Summit",
    location: "Abuja, Nigeria",
    date: "October 8, 2026",
    time: "8:30 AM - 5:00 PM",
  },
  {
    slug: "mobile-dev-lagos",
    image: "/images/event2.png",
    title: "Mobile Dev Lagos",
    location: "Lagos, Nigeria",
    date: "November 14, 2026",
    time: "10:00 AM - 4:00 PM",
  },
  {
    slug: "cybersec-nigeria",
    image: "/images/event3.png",
    title: "Nigeria Cybersecurity Conference",
    location: "Abuja, Nigeria",
    date: "December 2, 2026",
    time: "9:00 AM - 6:00 PM",
  },
  {
    slug: "datafest-lagos",
    image: "/images/event4.png",
    title: "DataFest Lagos",
    location: "Lagos, Nigeria",
    date: "January 22-24, 2027",
    time: "72 Hours",
  },
  {
    slug: "cloud-native-africa",
    image: "/images/event5.png",
    title: "Cloud Native Africa Meetup",
    location: "Lagos, Nigeria",
    date: "February 10, 2027",
    time: "5:00 PM - 8:00 PM",
  },
  {
    slug: "frontend-conf-lagos",
    image: "/images/event6.png",
    title: "Frontend Conference Lagos",
    location: "Lagos, Nigeria",
    date: "March 6, 2027",
    time: "9:00 AM - 5:00 PM",
  },
];